// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Wrapper(content templ.Component) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html style=\"background-color: black;\"><head><style>\n    @media only screen and (min-device-width: 1080px) {\n      html {\n        height: 100vh;\n        width: 100vw;\n        display: flex;\n        justify-content: center;\n      }\n    }\n\n    p {\n      font-size: 1em;\n    }\n\n    a {\n      font-size: 1em;\n    }\n\n    h1 {\n      font-size: 4em;\n    }\n\n    h2 {\n      font-size: 3em;\n    }\n\n    h3 {\n      font-size: 2em;\n    }\n\n    h4 {\n      font-size: 1.5em;\n    }\n  </style><meta charset=\"UTF-8\"><script src=\"/public/htmx.min.js\"></script><title>BitwiseDev</title></head><body style=\"color: white; background-color: black; font-family: sans-serif; padding-left: 1em; padding-right: 1em; padding-top: 1em; display: flex; width: 100%; flex-direction: column; gap: 1em; max-width: 1024px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Headings().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
